"""empty message

Revision ID: 64033ee1359e
Revises: 23dabfe623c6
Create Date: 2023-12-18 18:13:10.340699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64033ee1359e'
down_revision = '23dabfe623c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.alter_column('is_admin',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.alter_column('is_admin',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
